# Generated by Django 4.1.3 on 2022-11-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proxy_name", models.TextField()),
                ("display_txt", models.TextField()),
                ("time_edit", models.DateTimeField()),
                ("id_persistent", models.TextField()),
                ("names_personal", models.TextField(null=True)),
                ("names_family", models.TextField(null=True)),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vran.entity",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("vran.entity",),
        ),
    ]
