# Generated by Django 4.1.3 on 2022-12-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_persistent", models.TextField()),
                ("id_entity_persistent", models.TextField()),
                ("id_tag_definition_persistent", models.TextField()),
                ("value", models.TextField()),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("time_edit", models.DateTimeField()),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vran.taginstance",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TagDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("id_persistent", models.TextField()),
                ("id_parent_persistent", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INR", "inner"),
                            ("FLT", "float"),
                            ("INT", "integer"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                ("time_edit", models.DateTimeField()),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vran.tagdefinition",
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
