# Generated by Django 4.2 on 2023-04-24 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("id_persistent", models.UUIDField()),
                ("anonymous", models.BooleanField()),
                ("has_header", models.BooleanField()),
                ("file_name", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("UPLD", "uploaded"),
                            ("CLXT", "columns extracted"),
                            ("CLAS", "columns assigned"),
                            ("NTMT", "entities matched"),
                            ("NTAS", "entities assigned"),
                            ("VLAS", "values assigned"),
                            ("MRGD", "merged"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
