# Generated by Django 4.1.3 on 2023-01-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0002_taginstance_tagdefinition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taginstance",
            name="valid_from",
        ),
        migrations.RemoveField(
            model_name="taginstance",
            name="valid_to",
        ),
        migrations.AlterField(
            model_name="taginstance",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
    ]
