# Generated by Django 4.2 on 2023-05-11 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0002_contributioncandidate"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagDefinitionContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("id_persistent", models.UUIDField()),
                (
                    "id_existing_persistent",
                    models.UUIDField(blank=True, default=None, null=True),
                ),
                ("id_parent_persistent", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("INR", "inner"), ("FLT", "float"), ("STR", "string")],
                        default=None,
                        max_length=3,
                        null=True,
                    ),
                ),
                ("index_in_file", models.IntegerField()),
                ("discard", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="contributioncandidate",
            name="id",
        ),
        migrations.AlterField(
            model_name="contributioncandidate",
            name="id_persistent",
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="TagInstanceContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                ("id_entity_persistent", models.TextField(blank=True, null=True)),
                ("line_idx", models.IntegerField()),
                ("discard", models.BooleanField(default=True)),
                (
                    "tag_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vran.tagdefinitioncontribution",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tagdefinitioncontribution",
            name="contribution_candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="vran.contributioncandidate",
            ),
        ),
    ]
