# Generated by Django 4.2 on 2023-06-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0004_alter_tagdefinitioncontribution_id_existing_persistent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tagdefinitioncontribution",
            name="id_parent_persistent",
        ),
        migrations.RemoveField(
            model_name="tagdefinitioncontribution",
            name="type",
        ),
    ]
