# Generated by Django 4.2.2 on 2023-06-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0010_entityduplicate"),
    ]

    operations = [
        migrations.AddField(
            model_name="vranuser",
            name="id_persistent",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
