# Generated by Django 4.2.2 on 2023-06-29 17:02
"Migration definition for adding uuid to users"

from uuid import uuid4

from django.db import migrations


def add_uuid(apps, _schema_editor):
    "Method for adding a uuid to all users."
    user_model = apps.get_model("vran", "vranuser")
    for user in user_model.objects.all():
        user.id_persistent = uuid4()
        user.save(update_fields=["id_persistent"])


class Migration(migrations.Migration):
    "Migration class for adding uuid to users"
    dependencies = [
        ("vran", "0011_vranuser_id_persistent"),
    ]

    operations = [
        migrations.RunPython(add_uuid, reverse_code=migrations.RunPython.noop),
    ]
