# Generated by Django 4.2.2 on 2023-06-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0012_vranuser_id_persistent_add_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vranuser",
            name="id_persistent",
            field=models.UUIDField(unique=True),
        ),
    ]
