# Generated by Django 4.2.2 on 2023-07-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0013_alter_vranuser_id_persistent"),
    ]

    operations = [
        migrations.AddField(
            model_name="mergerequest",
            name="state",
            field=models.TextField(
                choices=[("OPN", "open"), ("CLS", "closed"), ("MRG", "merged")],
                default="OPN",
                max_length=3,
            ),
        ),
    ]
