# Generated by Django 4.2.2 on 2023-07-19 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0014_mergerequest_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergerequest",
            name="contribution_candidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="vran.contributioncandidate",
            ),
        ),
    ]
