# Generated by Django 4.2.2 on 2023-07-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0015_alter_mergerequest_contribution_candidate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergerequest",
            name="state",
            field=models.TextField(
                choices=[
                    ("OPN", "open"),
                    ("CNF", "conflicts"),
                    ("CLS", "closed"),
                    ("RSL", "resolved"),
                    ("MRG", "merged"),
                    ("ERR", "error"),
                ],
                default="OPN",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="ConflictResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("replace", models.BooleanField()),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vran.entity",
                    ),
                ),
                (
                    "merge_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vran.mergerequest",
                    ),
                ),
                (
                    "tag_definition_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vran.tagdefinition",
                    ),
                ),
                (
                    "tag_instance_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vran.taginstance",
                    ),
                ),
                (
                    "tag_definition_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vran.tagdefinition",
                    ),
                ),
                (
                    "tag_instance_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vran.taginstance",
                    ),
                ),
            ],
        ),
    ]
