# Generated by Django 4.2.2 on 2023-07-31 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0016_alter_mergerequest_state_conflictresolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conflictresolution",
            name="tag_instance_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="vran.taginstance",
            ),
        ),
    ]
