# Generated by Django 4.2.2 on 2023-08-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0018_vranuser_tag_definitions"),
    ]

    operations = [
        migrations.AddField(
            model_name="vranuser",
            name="permission_group",
            field=models.TextField(
                choices=[
                    ("APLC", "applicant"),
                    ("READ", "reader"),
                    ("CNTR", "contributor"),
                    ("EDTR", "editor"),
                    ("COMM", "commissioner"),
                ],
                default="APLC",
            ),
        ),
    ]
