# Generated by Django 4.2.2 on 2023-08-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0019_vranuser_permission_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vranuser",
            name="permission_group",
            field=models.TextField(
                choices=[
                    ("APLC", "applicant"),
                    ("READ", "reader"),
                    ("CNTR", "contributor"),
                    ("EDTR", "editor"),
                    ("COMM", "commissioner"),
                ],
                default="APLC",
                max_length=4,
            ),
        ),
    ]
