# Generated by Django 4.2.2 on 2023-11-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vran", "0022_contributioncandidate_error_msg_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MergeRequest",
            new_name="TagMergeRequest",
        ),
        migrations.AddField(
            model_name="entity",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
    ]
