# Generated by Django 4.2.2 on 2023-11-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0023_rename_mergerequest_tagmergerequest_entity_disabled"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ConflictResolution",
            new_name="TagConflictResolution",
        ),
    ]
