# Generated by Django 4.2.2 on 2023-11-10 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0024_rename_conflictresolution_tagconflictresolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagmergerequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tagmergerequest",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EntityMergeRequest",
            fields=[
                ("id_destination_persistent", models.TextField()),
                ("id_origin_persistent", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("id_persistent", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "state",
                    models.TextField(
                        choices=[
                            ("OPN", "open"),
                            ("CNF", "conflicts"),
                            ("CLS", "closed"),
                            ("RSL", "resolved"),
                            ("MRG", "merged"),
                            ("ERR", "error"),
                        ],
                        default="OPN",
                        max_length=3,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EntityConflictResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("replace", models.BooleanField()),
                (
                    "entity_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vran.entity",
                    ),
                ),
                (
                    "entity_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vran.entity",
                    ),
                ),
                (
                    "merge_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vran.entitymergerequest",
                    ),
                ),
                (
                    "tag_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vran.tagdefinition",
                    ),
                ),
                (
                    "tag_instance_destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vran.taginstance",
                    ),
                ),
                (
                    "tag_instance_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="vran.taginstance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
