# Generated by Django 4.2.2 on 2023-11-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0025_alter_tagmergerequest_assigned_to_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityconflictresolution",
            name="tag_instance_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="vran.taginstance",
            ),
        ),
        migrations.AlterField(
            model_name="tagconflictresolution",
            name="tag_instance_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="vran.taginstance",
            ),
        ),
    ]
