# Generated by Django 4.2.2 on 2023-12-07 13:24

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    "Migration for enabling postgres fuzzy string match"
    dependencies = [
        ("vran", "0027_tagdefinition_hidden"),
    ]

    operations = [CreateExtension("fuzzystrmatch")]
