# Generated by Django 4.2.8 on 2024-01-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0028_fuzzy_string_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taginstance",
            name="id_entity_persistent",
            field=models.CharField(max_length=36),
        ),
    ]
