# Generated by Django 4.2.8 on 2024-01-03 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vran", "0029_alter_taginstance_id_entity_persistent"),
    ]

    operations = [
        migrations.RenameModel(old_name="TagInstance", new_name="TagInstanceHistory")
    ]
