# Generated by Django 4.2.8 on 2024-01-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0031_tag_instance_most_recent_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.TextField(unique=True)),
                ("value", models.JSONField()),
            ],
        ),
    ]
