# Generated by Django 4.2.8 on 2024-01-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0032_configvalue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="display_txt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
