# Generated by Django 4.2.8 on 2024-01-23 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0033_alter_entity_display_txt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contributioncandidate",
            name="anonymous",
        ),
    ]
