# Generated by Django 4.2.8 on 2024-01-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0034_remove_contributioncandidate_anonymous"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagdefinitioncontribution",
            name="discard",
            field=models.BooleanField(default=True),
        ),
    ]
