# Generated by Django 4.2.8 on 2024-02-14 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    "Migrations for adding a most recent tag definition view."

    dependencies = [
        ("vran", "0036_rename_tagdefinition_tagdefinitionhistory"),
    ]

    operations = [
        migrations.RunSQL(
            """
            create view "vran_tagdefinition" as (
                select *
                from (
                        select max("id") max_id
                        from vran_tagdefinitionhistory vt
                        group by id_persistent
                    ) with_version
                    left join  (
                        select *
                        from vran_tagdefinitionhistory vt1
                    ) without_version
                    on "with_version"."max_id"="without_version"."id"
            )""",
            reverse_sql="drop view vran_tagdefinition",
        ),
        migrations.CreateModel(
            name="TagDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("id_persistent", models.TextField()),
                ("id_parent_persistent", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("INR", "inner"), ("FLT", "float"), ("STR", "string")],
                        default="INR",
                        max_length=3,
                    ),
                ),
                ("time_edit", models.DateTimeField()),
                ("curated", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
