# Generated by Django 4.2.8 on 2024-02-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vran", "0037_tagdefinition_and_more"),
    ]

    create_table_query = """
            create view "vran_tagdefinition" as (
                select *
                from (
                        select max("id") max_id
                        from vran_tagdefinitionhistory vt
                        group by id_persistent
                    ) with_version
                    left join  (
                        select *
                        from vran_tagdefinitionhistory vt1
                    ) without_version
                    on "with_version"."max_id"="without_version"."id"
            )"""

    drop_table_query = "drop view vran_tagdefinition"
    operations = [
        migrations.RunSQL(drop_table_query, reverse_sql=create_table_query),
        migrations.AddField(
            model_name="tagdefinitionhistory",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tagmergerequest",
            name="disable_origin_on_merge",
            field=models.BooleanField(default=False),
        ),
        migrations.RunSQL(
            create_table_query,
            reverse_sql=drop_table_query,
        ),
    ]
